const test=require('node:test'),assert=require('node:assert/strict');const {loadSgdiApp}=require('./load-app');
const exposed=['openAdminUserModal','adminWizardNext','adminWizardGo','adminWizardValidate','adminWizardPreserveAccess','adminWizardSelectSites','adminWizardSiteFilter','adminWizardSubmit','adminUserFromApi','SGDI'];
async function fixture(edit=false,extra={}){const c=loadSgdiApp(exposed);assert.ifError(c.loadError);const a=c.T(),w=c.window;w.history.replaceState(null,'','https://drh.irongs.com/#/admin/users');a.setSession({username:'UIADMIN',role:'ADM',adminSystem:true});const u={username:'OPS01',email:'ops@example.com',nom:'Opérations',role:'ops',niveau:'H3',actif:true,modulesAutorises:['ops','pointage'],structuresAutorisees:['ops'],actionsAutorisees:[],societesAutorisees:['IRON GLOBAL SOLUTION'],sitesAutorises:[1,9],validationCodeEnabled:true,peutReactiverSortant:true,...extra};a.setDb({users:[u],settings:{},niveauxAcces:[],droitsAcces:{},sites:[{id:'1',backendId:1,nom:'Site A',societe:'IRON GLOBAL SOLUTION'},{id:'2',backendId:2,nom:'Site B',societe:'IRON GLOBAL SÉCURITÉ'},{id:'9',backendId:9,nom:'Site fermé',societe:'IRON GLOBAL SOLUTION',actif:false}]});a.SGDI.sites.list=async()=>[];await w.SGDIModules.loadAndInitModule('administration');w.SGDIModules.markActiveModule('administration');await a.openAdminUserModal(edit?'OPS01':'');await new Promise(r=>setTimeout(r,5));const f=w.document.querySelector('.admin-user-wizard');assert.ok(f,'wizard mounted');return {...c,a,w,f,u};}
function identity(c){for(const [n,v] of Object.entries({username:'ATL99',email:'new@example.com',nom:'Compte Test',password:'Test!2026',validationPassword:'Validate!2026'}))c.f.elements[n].value=v}
test('wizard : une étape visible, cinq étapes, conservation des données au retour',async()=>{const c=await fixture();try{assert.equal(c.f.querySelectorAll('[data-panel]:not([hidden])').length,1);assert.equal(c.f.querySelectorAll('[data-step]').length,5);identity(c);c.a.adminWizardNext();assert.equal(c.f.__adminWizard.step,1);c.a.adminWizardGo(0);assert.equal(c.f.elements.nom.value,'Compte Test');assert.equal(c.f.elements.password.value,'Test!2026');c.a.adminWizardGo(4);assert.equal(c.f.__adminWizard.step,0)}finally{c.w.close()}});
test('wizard : validation par étape et erreur associée au champ',async()=>{const c=await fixture();try{c.a.adminWizardNext();assert.equal(c.f.__adminWizard.step,0);assert.equal(c.f.elements.nom.getAttribute('aria-invalid'),'true');identity(c);assert.equal(c.a.adminWizardValidate(0),true);assert.equal(c.a.adminWizardValidate(1),false);assert.equal(c.f.__adminWizard.step,1)}finally{c.w.close()}});
test('wizard : catalogues canoniques complets, modules séparés des structures et actions',async()=>{const c=await fixture(true);try{assert.equal(c.f.querySelectorAll('input[name^="module_"]').length,16);assert.equal(c.f.querySelectorAll('input[name^="struct_"]').length,22);assert.equal(c.f.querySelectorAll('input[name^="action_"]').length,8);assert.equal(c.f.querySelector('[name="module_pointage"]').closest('[data-panel]').dataset.panel,'1');assert.equal(c.f.querySelector('[name="struct_pointage"]').closest('[data-panel]').dataset.panel,'2');assert.equal(c.f.elements.validationCodeEnabled.checked,true);assert.equal(c.f.elements.peutReactiverSortant.checked,true)}finally{c.w.close()}});
test('wizard : enregistrement sans modification conserve tableaux, rôle historique et sites désactivés',async()=>{const c=await fixture(true,{role:'drh',modulesAutorises:null,structuresAutorisees:['ops','structure_future'],actionsAutorisees:['read'],societesAutorisees:['IRON GLOBAL SOLUTION'],sitesAutorises:[9,1,999]});try{const data={role:c.f.elements.role.value,niveau:c.f.elements.niveau.value};c.a.adminWizardPreserveAccess(c.f,data);for(const key of ['modulesAutorises','structuresAutorisees','actionsAutorisees','societesAutorisees','sitesAutorises'])assert.deepEqual(JSON.parse(JSON.stringify(data[key])),c.u[key],key);assert.equal(data.role,'drh');assert.ok(c.f.querySelector('[name="site_999"]:checked'));assert.ok(c.f.querySelector('[name="site_9"]:checked'));assert.equal(c.f.elements.password.value,'')}finally{c.w.close()}});
test('wizard : select all limité aux sociétés cochées, recherche ne retire aucune attribution',async()=>{const c=await fixture(true);try{c.a.adminWizardSelectSites(true);assert.equal(c.f.querySelector('[name="site_2"]').checked,false);c.w.document.getElementById('auw-site-search').value='introuvable';c.a.adminWizardSiteFilter();assert.equal(c.f.querySelector('[name="site_1"]').checked,true);assert.match(c.w.document.getElementById('auw-site-count').textContent,/2 sites/)}finally{c.w.close()}});
test('wizard : règle BEO et récapitulatif sans mot de passe',async()=>{const c=await fixture(true,{role:'charge_effectifs_site',modulesAutorises:['site_workforce'],societesAutorisees:[],sitesAutorises:[]});try{assert.equal(c.a.adminWizardValidate(3),false);assert.match(c.w.document.getElementById('auw-error').textContent,/au moins une société/);identity(c);c.w.adminWizardShow(4);assert.doesNotMatch(c.w.document.getElementById('auw-recap').textContent,/Test!2026|Validate!2026/)}finally{c.w.close()}});
test('wizard : deux soumissions concurrentes déclenchent une seule sauvegarde',async()=>{const c=await fixture(true);try{let calls=0,finish;c.w.confirmAdminUser=()=>{calls++;return new Promise(resolve=>finish=resolve)};c.w.adminWizardShow(4);const first=c.a.adminWizardSubmit();const second=c.a.adminWizardSubmit();assert.equal(calls,1);assert.equal(c.w.document.getElementById('auw-submit').disabled,true);finish();await Promise.all([first,second]);assert.equal(c.w.document.getElementById('auw-submit').disabled,false)}finally{c.w.close()}});

test('wizard : un profil historique null reste null au lieu de devenir H1',async()=>{const c=await fixture(true,{niveau:'',originalAccess:{role:'ops',niveau:null,modulesAutorises:['ops'],structuresAutorisees:['ops'],actionsAutorisees:[],societesAutorisees:['IRON GLOBAL SOLUTION'],sitesAutorises:[1,9]}});try{const data={role:c.f.elements.role.value,niveau:c.f.elements.niveau.value};c.a.adminWizardPreserveAccess(c.f,data);assert.equal(data.niveau,null);assert.equal(c.f.elements.niveau.value,'')}finally{c.w.close()}});
