const test=require('node:test');
const assert=require('node:assert/strict');
const {loadSgdiApp}=require('./load-app');
function boot(t,actions=['read','create','update','validate','export']){
 const r=loadSgdiApp(['emptyDB','renderCongesModule','drhLeaveCockpitData','drhLeaveCockpitCan','openDrhLeaveCockpitDetail','openCongeAttributionPicker','exportCongesRecapCSV']);assert.ifError(r.loadError);t.after(()=>r.window.close());
 const db=r.T().emptyDB();db.agents=[{id:'a',nom:'ALPHA',societe:'IRON GLOBAL SOLUTION',statut:'actif',dateRecrutement:'2020-01-01'},{id:'b',nom:'BETA',societe:'OTHER',statut:'actif'}];
 db.conges=[{id:'c',agentId:'a',type:'Annuel',du:'2026-09-30',au:'2026-10-05',createdAt:'2026-09-01',statut:'approuve'},{id:'duplicate',agentId:'a',type:'Exceptionnel',du:'2026-10-02',au:'2026-10-03',createdAt:'2026-10-01',statut:'approuve'},{id:'pending',agentId:'a',type:'Sans solde',du:'2026-10-03',au:'2026-10-04',createdAt:'2026-08-01',statut:'en_attente'},{id:'outside',agentId:'b',type:'Annuel',du:'2026-10-03',au:'2026-10-05',createdAt:'2026-10-01',statut:'en_attente'}];
 r.T().setDb(db);r.T().setSession({username:'RH',role:'rh',transverse:'drh',societe:'IRON GLOBAL SOLUTION',actionsAutorisees:actions});
 return {...r,db,root:r.window.document.getElementById('view')};
}
function data(r,balances=[{a:r.db.agents[0],name:'ALPHA',solde:20}]){return r.T().drhLeaveCockpitData([r.db.agents[0]],r.db.conges,balances,'2026-10-03','2026-10-03',2026)}
test('KPI et semaine: scope, approuvé uniquement, employés distincts et UTC',t=>{const r=boot(t),d=data(r);assert.equal(d.pending.length,1);assert.equal(d.currentCount,1);assert.equal(d.current.length,2);assert.equal(d.week[0].iso,'2026-09-28');assert.equal(d.week[6].iso,'2026-10-04');assert.equal(d.week[5].count,1);assert.equal(d.categories[0].count,1);assert.equal(d.high.length,1)});
test('classification: seuil existant, positifs, négatifs et inconnus',t=>{const r=boot(t),d=data(r,[20,19.99,0,-1,null].map((solde,i)=>({a:{id:i},name:String(i),solde})));assert.deepEqual(Array.from(d.categories,x=>x.count),[1,1,2,1]);assert.equal(d.high.length,1)});
test('évolution: création réelle, statuts actuels et dates manquantes explicites',t=>{const r=boot(t);r.db.conges.push({id:'undated',agentId:'a',type:'Annuel',du:'2026-10-01',au:'2026-10-02',statut:'refuse'});const d=data(r);assert.equal(d.undated,1);assert.equal(d.months[5].approuve,1);assert.equal(d.months[3].en_attente,1);assert.equal(d.months[5].refuse,0);assert.equal(d.latest[0].id,'duplicate')});
test('types: jours approuvés bornés à l’année, nomenclature réelle',t=>{const r=boot(t);r.db.conges.push({id:'cross',agentId:'a',type:'Type personnalisé',du:'2025-12-30',au:'2026-01-02',createdAt:'2025-12-01',statut:'approuve'});const d=data(r);assert.equal(d.typeTotal,10);assert.equal(d.typeRows.find(x=>x[0]==='Type personnalisé')[1],2);assert.equal(d.typeRows.some(x=>x[0]==='Sans solde'),false)});
test('priorités déterministes: anciennes demandes puis soldes décroissants',t=>{const r=boot(t);r.db.conges.push({id:'old',agentId:'a',type:'Annuel',du:'2026-12-01',au:'2026-12-02',createdAt:'2026-01-01',statut:'en_attente'});assert.equal(data(r).pending[0].id,'old');r.T().renderCongesModule(r.root,true);assert.match(r.root.querySelector('.leave-actions').textContent,/ALPHA/)});
test('cockpit complet et détail réel en lecture seule, shell non remplacé',t=>{const r=boot(t,['read']);r.T().renderCongesModule(r.root,true);assert.equal(r.root.querySelectorAll('.leave-modern-card').length,6);assert.equal(r.root.querySelectorAll('.ops-dash-kpi').length,4);assert.equal(r.root.querySelectorAll('.leave-week-strip button').length,7);assert.doesNotMatch(r.root.textContent,/Nouvelle demande|Attribuer un congé|Exporter/);assert.doesNotMatch(r.root.querySelector('.leave-cockpit-kpis').textContent,/%/);r.T().openDrhLeaveCockpitDetail('c');assert.match(r.window.document.getElementById('modal-host').textContent,/ALPHA/)});
test('sans export et sans validation: actions absentes, consultation conservée',t=>{const r=boot(t,['read','create','update']);r.T().renderCongesModule(r.root,true);assert.doesNotMatch(r.root.textContent,/Exporter|Attribuer un congé/);assert.match(r.root.textContent,/Nouvelle demande/);r.window.sessionStorage.setItem('drhCongesDashboardTab','requests');r.T().renderCongesModule(r.root,true);assert.doesNotMatch(r.root.innerHTML,/onclick="approuverConge|onclick="refuserConge/)});
test('DRH complet: workflow et export présents',t=>{const r=boot(t);r.window.sessionStorage.setItem('drhCongesDashboardTab','requests');r.T().renderCongesModule(r.root,true);assert.match(r.root.innerHTML,/onclick="approuverConge/);assert.match(r.root.textContent,/Exporter|Attribuer un congé/)});
test('hors société: aucune donnée ni détail accessible',t=>{const r=boot(t);r.T().renderCongesModule(r.root,true);assert.doesNotMatch(r.root.textContent,/BETA|OTHER/);r.T().openDrhLeaveCockpitDetail('outside');assert.equal(r.window.document.getElementById('modal-host').innerHTML,'')});
test('états vides: aucune fausse courbe ni donut',t=>{const r=boot(t);r.db.agents=[];r.db.conges=[];r.T().renderCongesModule(r.root,true);assert.match(r.root.textContent,/Aucune priorité|Aucune demande datée|Aucun solde|Aucune demande enregistrée|Aucun jour/);assert.equal(r.root.querySelector('.leave-donut'),null);assert.equal(r.root.querySelector('.leave-month-chart'),null)});
test('semaine choisie sur le changement d’année',t=>{const r=boot(t);const d=r.T().drhLeaveCockpitData([],[],[],'2026-01-01','2026-01-01',2026);assert.equal(d.week[0].iso,'2025-12-29');assert.equal(d.week[6].iso,'2026-01-04')});

test('site superviseur limité: seules les personnes autorisées sont visibles',t=>{const r=boot(t,['read']);r.db.sites=[{id:'s1',nom:'ALGER',societe:'IRON GLOBAL SOLUTION'},{id:'s2',nom:'ORAN',societe:'IRON GLOBAL SOLUTION'}];r.db.agents[0].affectationCourante={siteId:'s1',siteName:'ALGER'};r.db.agents[1].societe='IRON GLOBAL SOLUTION';r.db.agents[1].affectationCourante={siteId:'s2',siteName:'ORAN'};r.T().setSession({username:'SUP',role:'dispatch',transverse:'superviseur',societe:'IRON GLOBAL SOLUTION',sitesAutorises:['s1'],actionsAutorisees:['read'],supervisorReadOnly:true});r.T().renderCongesModule(r.root,false);assert.match(r.root.textContent,/ALPHA/);assert.doesNotMatch(r.root.textContent,/BETA|ORAN/);r.T().openDrhLeaveCockpitDetail('outside');assert.equal(r.window.document.getElementById('modal-host').innerHTML,'')});
test('export direct en lecture seule et attribution interdite: aucun dialogue',t=>{const r=boot(t,['read']);r.T().exportCongesRecapCSV();r.T().openCongeAttributionPicker();assert.equal(r.window.document.getElementById('modal-host').innerHTML,'')});
