const test=require('node:test'),assert=require('node:assert/strict');
const {loadPointeur}=require('./load-pointeur');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
const session={token:'fixture',user:{username:'FIXTURE'}};
const sites=[{id:1,name:'Site A',society:'IRON GLOBAL SÉCURITÉ'},{id:2,name:'Site B',society:'IRON GLOBAL SOLUTION'}];
function boot(){const calls=[];const r=loadPointeur({url:'https://pointeur.irongs.com/',session,fetch:async url=>{calls.push(String(url));const u=new URL(url,'https://pointeur.irongs.com');let data={};if(u.pathname.endsWith('attendance-sites'))data=sites;else if(u.pathname.endsWith('attendance-feed')||u.pathname.endsWith('attendance-manual/search')||u.pathname.endsWith('attendance-anomalies'))data=[];return {ok:true,status:200,json:async()=>data}}});return {...r,calls}}
test('sociétés et sites : options issues uniquement du catalogue backend autorisé',async()=>{const r=boot();try{await wait(100);const d=r.window.document;assert.deepEqual([...d.querySelectorAll('#societySelector option')].map(o=>o.value),['',...sites.map(s=>s.society)]);await r.window.changeAttendanceSociety(sites[1].society);assert.deepEqual([...d.querySelectorAll('#siteSelector option')].map(o=>o.value),['','2']);assert.equal(d.getElementById('trackingSite').innerHTML,d.getElementById('siteSelector').innerHTML);assert.ok(r.calls.some(u=>new URL(u,'https://local').searchParams.get('society')===sites[1].society));await r.window.changeAttendanceSociety('SWORD CORPORATION');assert.equal(d.getElementById('siteSelector').options[1].value,'2')}finally{r.dom.window.close()}});
test('une ligne journalière conserve la première entrée et la dernière sortie après plusieurs cycles',()=>{const r=loadPointeur();try{const base={employee_id:1,matricule:'T1',nom:'Fixture'};const rows=r.window.trackingDailyRows([{...base,action:'depart',scanned_at:'2026-10-06T18:05:43+01:00'},{...base,action:'arrivee',scanned_at:'2026-10-06T13:49:12+01:00'},{...base,action:'depart',scanned_at:'2026-10-06T12:00:00+01:00'},{...base,action:'arrivee',scanned_at:'2026-10-06T08:00:00+01:00'}]);assert.equal(rows.length,1);assert.equal(rows[0].arrival,'08:00:00');assert.equal(rows[0].departure,'18:05:43');assert.equal(rows[0].status,'Sorti')}finally{r.dom.window.close()}});
test('fenêtre nommée : réutilisation puis réouverture, tableau principal conservé',async()=>{const r=boot();try{await wait(100);let opened=0,focused=0;let child={closed:false,focus:()=>focused++};r.window.open=(url,name,features)=>{assert.equal(url,'/pointeur/suivi');assert.equal(name,'atlas-pointeur-suivi');assert.match(features,/popup=yes/);opened++;return child};r.window.openTrackingWindow();r.window.openTrackingWindow();assert.equal(opened,1);assert.equal(focused,1);child.closed=true;child={closed:false,focus:()=>focused++};r.window.openTrackingWindow();assert.equal(opened,2);assert.ok(r.window.document.getElementById('trackingTable'))}finally{r.dom.window.close()}});
