import React from 'react';
import { ActivityIndicator, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, TextInputProps, View } from 'react-native';
export const colors = { ink: '#16263B', muted: '#62738A', background: '#F2F5F9', gold: '#D8AA4D', white: '#FFFFFF', border: '#DCE3EB', red: '#A52632' };
export function Page({ title, subtitle, children }: {title: string; subtitle?: string; children: React.ReactNode}) { return <KeyboardAvoidingView style={styles.page} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><Text style={styles.eyebrow}>IRON GLOBAL · RECRUTEMENT</Text><Text style={styles.title}>{title}</Text>{subtitle && <Text style={styles.subtitle}>{subtitle}</Text>}{children}</ScrollView></KeyboardAvoidingView>; }
export function Card({children}: {children: React.ReactNode}) { return <View style={styles.card}>{children}</View>; }
export function Field({label, ...props}: TextInputProps & {label: string}) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput accessibilityLabel={label} placeholderTextColor={colors.muted} style={styles.input} {...props} /></View>; }
export function Button({title, onPress, busy = false, secondary = false, disabled = false}: { title: string; onPress: () => void; busy?: boolean; secondary?: boolean; disabled?: boolean }) { return <Pressable accessibilityRole="button" accessibilityState={{ disabled: busy || disabled }} disabled={busy || disabled} onPress={onPress} style={({pressed}) => [styles.button, secondary && styles.secondary, (busy || disabled) && {opacity: 0.5}, pressed && {opacity: 0.8}]}>{busy ? <ActivityIndicator color={secondary ? colors.ink : colors.white}/> : <Text style={[styles.buttonText, secondary && {color: colors.ink}]}>{title}</Text>}</Pressable>; }
export function ErrorText({message}: {message?: string}) { return message ? <Text accessibilityRole="alert" style={styles.error}>{message}</Text> : null; }
export const styles = StyleSheet.create({
  page: {flex: 1, backgroundColor: colors.background}, content: {padding: 22, gap: 16, paddingBottom: 40}, eyebrow: {fontSize: 10, letterSpacing: 2, fontWeight: '700', color: colors.muted}, title: {fontSize: 30, fontWeight: '700', color: colors.ink}, subtitle: {fontSize: 15, lineHeight: 23, color: colors.muted}, card: {padding: 20, borderRadius: 18, backgroundColor: colors.white, gap: 14, borderWidth: 1, borderColor: colors.border}, label: {fontSize: 13, color: colors.ink, fontWeight: '600'}, field: {gap: 7}, input: {minHeight: 50, borderRadius: 10, borderWidth: 1, borderColor: colors.border, padding: 13, color: colors.ink, backgroundColor: '#FAFBFD', fontSize: 16}, button: {minHeight: 50, borderRadius: 10, backgroundColor: colors.ink, alignItems: 'center', justifyContent: 'center', padding: 13}, secondary: {backgroundColor: '#EBF0F6'}, buttonText: {color: colors.white, fontSize: 15, fontWeight: '600'}, error: {color: colors.red, lineHeight: 22}, heading: {fontSize: 19, color: colors.ink, fontWeight: '700'}, badge: {color: colors.ink, backgroundColor: '#F6EBCD', padding: 8, borderRadius: 7, alignSelf: 'flex-start'}, row: {flexDirection: 'row', alignItems: 'center', gap: 12}, link: {color: colors.ink, fontWeight: '600'}, photo: {width: 90, height: 90, borderRadius: 16},
});
